language: java
jdk:
  - oraclejdk11
  - oraclejdk8
  - openjdk11
  - openjdk10
  - openjdk8
  
addons:
  apt:
    packages:
      - junit4
  
script:
  - cd Assignments/RecordsManagment
  - ant
  - cd ../JavaRmi/RecordsManagment-Server
  - ant test
  - java -jar dist\RecordsManagment-Server.jar &
  - cd ../RecordsManagment-Client
  - ant test
