language: java
jdk:
  - oraclejdk8
  - openjdk10
  - openjdk8
  
script:
  - cd Assignments/RecordsManagment
  - ant compile jar
  - cd ../JavaRmi/RecordsManagment-Server
  - ant compile jar
  - ant run &
  - cd ../RecordsManagment-Client
  - ant compile jar
