language: java
jdk:
  - oraclejdk8
  - openjdk10
  - openjdk8
  
script:
  - cd Assignments/RecordsManagment
  - ant
  - cd ../JavaRmi/RecordsManagment-Server
  - ant test
  - cd ../RecordsManagment-Client
