language: java
jdk:
  - oraclejdk8
  - openjdk10
  - openjdk8
  
script:
  - cd Assignments/RecordsManagment
  - ant compile jar
  - cd ../JavaRmi/RecordsManagment-Server
  - ant compile jar
  - cd ../RecordsManagment-Client
  - ant compile jar
  - cd ..
  - ant -f RecordsManagment-Server run &
  - ant -f RecordsManagment-Client test
