language: java
jdk:
  - oraclejdk8
  - openjdk10
  - openjdk8
  
script:
  - cat /etc/hosts
  - exit here
  - cd Assignments/RecordsManagment
  - ant
  - cd ../JavaRmi/RecordsManagment-Server
  - ant test
  - java -jar dist\RecordsManagment-Server.jar &
  - cd ../RecordsManagment-Client
  - ant test
